services:
  web:
    build: .
    container_name: midpoint-web
    restart: unless-stopped
    networks:
      - root_default
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=root_default"
      - "traefik.http.routers.midpoint.entrypoints=websecure"
      - "traefik.http.routers.midpoint.rule=Host(`midpoint.onpointoffices.co.za`)"
      - "traefik.http.routers.midpoint.tls=true"
      - "traefik.http.routers.midpoint.tls.certresolver=mytlschallenge"
      - "traefik.http.services.midpoint.loadbalancer.server.port=3000"
networks:
  root_default:
    external: true
