import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { jwtVerify } from "jose";
import { legacyDestination } from "@/lib/legacy-routes";

const secret = new TextEncoder().encode(
  process.env.AUTH_SECRET || "dev-insecure-secret-change-me"
);
const SESSION_COOKIE = "midpoint_admin_session";

const HTML_CACHE_CONTROL =
  "private, no-cache, no-store, max-age=0, must-revalidate, no-transform";

function continueRequest(request: NextRequest) {
  const response = NextResponse.next();

  // Cloudflare's Email Address Obfuscation rewrites server-rendered email
  // links and injects a decoder script before React hydrates the page. That
  // makes the browser DOM differ from the HTML generated by Next.js and can
  // trigger an intermittent client-side hydration crash. Cloudflare honours
  // `no-transform`, so protect HTML while leaving JS, CSS and images alone.
  if (request.headers.get("accept")?.includes("text/html")) {
    response.headers.set("Cache-Control", HTML_CACHE_CONTROL);
  }

  return response;
}

const PUBLIC_ROUTES = new Set([
  "/admin/login",
  "/api/admin/login",
  "/admin/forgot-password",
  "/api/admin/forgot-password",
  "/admin/reset-password",
  "/api/admin/reset-password",
]);

// --- Redirect-manager cache -------------------------------------------
// Edge middleware can't talk to Prisma directly (self-hosted Postgres, not
// an edge-compatible driver), so instead of a DB lookup on every single
// page request, the full redirect list is fetched at most once every 60
// seconds from /api/redirects/all (a plain Node.js route with normal
// Prisma access) and cached in this module-scope Map. Everyday requests
// then do a synchronous in-memory lookup only — a saved/edited redirect
// can take up to ~60s to go live, which is a reasonable trade for not
// adding a database round-trip to every page load on the site.
//
// Two fixes applied here after a perf investigation found this middleware
// was inflating TTFB on every request when the cache was stale:
//   1. Fetches http://127.0.0.1:$PORT directly instead of the request's
//      public HTTPS origin. The original version self-fetched the site's
//      own public hostname, meaning every refresh paid for DNS + a TLS
//      handshake + a hairpin through the reverse proxy back into this
//      exact same (single, non-replicated) Node process — all while that
//      process was still in the middle of handling the request that
//      triggered the refresh. Talking to localhost skips all of that.
//   2. A single in-flight Promise is now shared across concurrent
//      requests. Previously, if N requests landed during the same stale
//      window, each one independently saw the cache as expired and fired
//      its own duplicate self-fetch + duplicate Prisma query (a classic
//      cache stampede) instead of sharing one refresh.
type RedirectEntry = { toPath: string; statusCode: number };
let redirectCache: Map<string, RedirectEntry> = new Map();
let redirectCacheAt = 0;
let refreshInFlight: Promise<void> | null = null;
const REDIRECT_CACHE_TTL_MS = 60_000;

function internalUrl(path: string): string {
  const port = process.env.PORT || "3000";
  return `http://127.0.0.1:${port}${path}`;
}

async function refreshRedirectCache(): Promise<void> {
  try {
    const res = await fetch(internalUrl("/api/redirects/all"));
    if (res.ok) {
      const rules: { fromPath: string; toPath: string; statusCode: number }[] = await res.json();
      redirectCache = new Map(rules.map((r) => [r.fromPath, { toPath: r.toPath, statusCode: r.statusCode }]));
      redirectCacheAt = Date.now();
    }
  } catch {
    // Keep serving the previous (possibly stale) cache rather than losing
    // every redirect over one transient fetch failure.
  }
}

async function getRedirectCache(): Promise<Map<string, RedirectEntry>> {
  const now = Date.now();
  if (now - redirectCacheAt < REDIRECT_CACHE_TTL_MS) return redirectCache;

  if (!refreshInFlight) {
    refreshInFlight = refreshRedirectCache().finally(() => {
      refreshInFlight = null;
    });
  }
  await refreshInFlight;
  return redirectCache;
}

function recordHit(fromPath: string) {
  // Fire-and-forget — never await this in the request path.
  fetch(internalUrl("/api/redirects/hit"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ fromPath }),
  }).catch(() => {});
}

// --- IndexNow key cache -------------------------------------------------
// Same self-fetch-and-cache pattern as the redirect cache above, and for
// the same reason (no Prisma in edge middleware). The key is editable from
// /admin/settings (lib/site-settings.ts, falls back to
// lib/indexnow-key.ts's DEFAULT_INDEXNOW_KEY when unset) — this lets
// middleware serve the correct <domain>/<key>.txt ownership file for
// whatever key is currently configured, without needing a code change/
// redeploy every time someone edits it in Settings.
let indexNowKeyCache = "";
let indexNowKeyCacheAt = 0;
let indexNowKeyRefreshInFlight: Promise<void> | null = null;
const INDEXNOW_KEY_CACHE_TTL_MS = 60_000;

async function refreshIndexNowKeyCache(): Promise<void> {
  try {
    const res = await fetch(internalUrl("/api/settings/indexnow-key"));
    if (res.ok) {
      const body: { key: string } = await res.json();
      if (body.key) {
        indexNowKeyCache = body.key;
        indexNowKeyCacheAt = Date.now();
      }
    }
  } catch {
    // Keep serving the previous (possibly stale) key rather than breaking
    // the ownership file over one transient fetch failure.
  }
}

async function getIndexNowKey(): Promise<string> {
  const now = Date.now();
  if (indexNowKeyCache && now - indexNowKeyCacheAt < INDEXNOW_KEY_CACHE_TTL_MS) return indexNowKeyCache;

  if (!indexNowKeyRefreshInFlight) {
    indexNowKeyRefreshInFlight = refreshIndexNowKeyCache().finally(() => {
      indexNowKeyRefreshInFlight = null;
    });
  }
  await indexNowKeyRefreshInFlight;
  return indexNowKeyCache;
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // A request for /<something>.txt at the root — check it against the
  // currently configured IndexNow key before anything else. Anything that
  // doesn't match (e.g. /llms.txt, which has its own dedicated route) falls
  // straight through to normal routing untouched.
  const txtMatch = /^\/([^/]+)\.txt$/i.exec(pathname);
  if (txtMatch) {
    const key = await getIndexNowKey();
    if (key && txtMatch[1] === key) {
      return new NextResponse(key, { headers: { "Content-Type": "text/plain" } });
    }
    return continueRequest(request);
  }

  if (PUBLIC_ROUTES.has(pathname)) {
    return continueRequest(request);
  }

  const isAdminProtected = pathname.startsWith("/admin") || pathname.startsWith("/api/admin");
  if (isAdminProtected) {
    const token = request.cookies.get(SESSION_COOKIE)?.value;
    if (!token) return redirectToLogin(request);
    try {
      await jwtVerify(token, secret);
      return continueRequest(request);
    } catch {
      return redirectToLogin(request);
    }
  }

  if (pathname.startsWith("/api/")) {
    return NextResponse.next();
  }

  const legacyPath = legacyDestination(pathname);
  if (legacyPath) {
    return NextResponse.redirect(new URL(legacyPath, request.url), 308);
  }

  const cache = await getRedirectCache();
  const match = cache.get(pathname);
  if (match) {
    recordHit(pathname);
    const destination = match.toPath.startsWith("http")
      ? match.toPath
      : new URL(match.toPath, request.url);
    return NextResponse.redirect(destination, match.statusCode);
  }

  return continueRequest(request);
}

function redirectToLogin(request: NextRequest) {
  if (request.nextUrl.pathname.startsWith("/api/admin")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const url = request.nextUrl.clone();
  url.pathname = "/admin/login";
  return NextResponse.redirect(url);
}

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\..*).*)",
    // Explicit extra entry so top-level *.txt requests (the IndexNow key
    // file above all) still reach this middleware despite the blanket
    // ".*\\..*" exclusion in the pattern above.
    "/:file.txt",
  ],
};
