import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/require-admin";
import { todayZA, money } from "@/lib/stay-pricing";
import { bookingFilters, pageNumber, reservationStatuses, shortDate } from "@/lib/suites-operations";
import { PageHeading, EmptyState, StatusBadge } from "@/components/admin/OperationsUI";
import { CalendarDays, ArrowUpRight } from "lucide-react";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  await requireAdmin();
  const q=await searchParams, today=new Date(todayZA()+"T00:00:00Z"),where=bookingFilters(q,today),perPage=20;
  const total=await prisma.reservation.count({where});
  const pages=Math.max(1,Math.ceil(total/perPage)),page=Math.min(pageNumber(q.page),pages);
  const rows=await prisma.reservation.findMany({where,include:{room:true,category:true},orderBy:[{createdAt:"desc"},{id:"desc"}],skip:(page-1)*perPage,take:perPage});
  const url=(overrides:Record<string,string>)=>{const p=new URLSearchParams();for(const [k,v] of Object.entries({...q,...overrides}))if(v)p.set(k,v);return "/admin/bookings?"+p.toString();};
  const tabs=[["","All reservations"],["arrivals","Arrivals today"],["departures","Departures today"],["inhouse","In house"],["cancellations","Cancellation requests"],["unpaid","Unpaid test balances"]];
  return <><PageHeading title="Every stay, in one place." description="Find a guest, review a reservation and keep the front desk moving. All records in this workspace are test bookings."><Link href="/admin/calendar" className="ops-button secondary"><CalendarDays size={15}/>Calendar</Link><Link href="/admin/bookings/new" className="ops-button">＋ New test reservation</Link></PageHeading>
    <div className="ops-tabs">{tabs.map(([value,label])=><Link key={value} href={url({view:value,page:"1",status:"",payment:""})} aria-current={(q.view||"")===value?"page":undefined}>{label}</Link>)}</div>
    <section className="ops-panel"><form className="ops-toolbar"><input type="hidden" name="view" value={q.view||""}/><label className="ops-search">Search reservations<input name="q" defaultValue={q.q} placeholder="Guest, email, reference or company" maxLength={120}/></label><label>Status<select name="status" defaultValue={q.status||""}><option value="">All statuses</option>{reservationStatuses.map(s=><option key={s} value={s}>{s.toLowerCase().replaceAll("_"," ")}</option>)}</select></label><label>Test payment<select name="payment" defaultValue={q.payment||""}><option value="">All balances</option>{["UNPAID","PARTIALLY_PAID","PAID","REFUNDED"].map(s=><option key={s} value={s}>{s.toLowerCase().replaceAll("_"," ")}</option>)}</select></label><button className="ops-button">Apply filters</button><Link href="/admin/bookings" className="text-xs underline p-3">Reset</Link></form>
    {rows.length?<div className="ops-table-wrap"><table className="ops-table"><thead><tr>{["Guest / reference","Room","Stay dates","Reservation","Test payment","Test total",""].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link href={"/admin/bookings/"+r.id} className="ops-guest"><span className="ops-avatar">{r.guestFirstName[0]}{r.guestLastName[0]}</span><span><strong>{r.guestFirstName} {r.guestLastName}</strong><small>{r.bookingReference}</small></span></Link>{r.cancellationRequested&&<span className="ops-pill amber mt-2">Cancellation requested</span>}</td><td>{r.room?.roomNumber||"Unassigned"}<small>{r.category.name}</small></td><td>{shortDate(r.checkIn)} – {shortDate(r.checkOut)}<small>{r.checkIn.getUTCFullYear()} · {Math.round((+r.checkOut-+r.checkIn)/86400000)} nights · {r.adults} guests</small></td><td><StatusBadge status={r.status}/>{r.status==="PENDING"&&r.expiresAt&&r.expiresAt<new Date()&&<small>Hold expired</small>}</td><td><StatusBadge status={r.paymentStatus}/></td><td><strong>{money(Math.round(Number(r.total)*100))}</strong><small>{r.company||"Direct guest"}</small></td><td><Link href={"/admin/bookings/"+r.id} aria-label={"Open reservation "+r.bookingReference}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table></div>:<EmptyState title="No reservations match" detail="Try a different search or clear the filters. New test bookings will appear here as they are created." href="/admin/bookings/new" label="Create a test reservation"/>}
    <div className="ops-pagination"><span>{total?((page-1)*perPage+1)+"–"+Math.min(page*perPage,total):"0"} of {total} reservations</span><div className="flex items-center gap-3">{page>1&&<Link className="ops-button secondary" href={url({page:String(page-1)})}>Previous</Link>}<span>Page {page} of {pages}</span>{page<pages&&<Link className="ops-button secondary" href={url({page:String(page+1)})}>Next</Link>}</div></div></section>
  </>;
}
