export type Tenant = {
  name: string;
  src: string;
};

export const tenants: Tenant[] = [
  { name: "Afripower SA", src: "/images/tenants/afripower-sa.jpg" },
  { name: "Atess", src: "/images/tenants/atess.jpg" },
  { name: "Avroy Shlain Southern Africa", src: "/images/tenants/avroy-shlain.jpg" },
  { name: "Beeline Spares", src: "/images/tenants/beeline-spares.png" },
  { name: "Bidvest", src: "/images/tenants/bidvest.png" },
  { name: "BoltTech", src: "/images/tenants/bolttech.png" },
  { name: "Capitec Bank", src: "/images/tenants/capitec-bank.png" },
  { name: "Carecall Retail & Distribution Services", src: "/images/tenants/carecall.png" },
  { name: "City of Johannesburg", src: "/images/tenants/city-of-joburg.jpg" },
  { name: "Fresenius Kabi", src: "/images/tenants/fresenius-kabi.jpg" },
  { name: "G85", src: "/images/tenants/g85.png" },
  { name: "Galitos", src: "/images/tenants/galitos.png" },
  { name: "Gobiosis", src: "/images/tenants/gobiosis.png" },
  { name: "Go Fresh", src: "/images/tenants/go-fresh.avif" },
  { name: "Healthcare Mobility Africa", src: "/images/tenants/healthcare-mobility-africa.webp" },
  { name: "Incledon", src: "/images/tenants/incledon.png" },
  { name: "Lemorgan", src: "/images/tenants/lemorgan.png" },
  { name: "LG Electronics", src: "/images/tenants/lg-electronics.png" },
  { name: "LMB", src: "/images/tenants/lmb.png" },
  { name: "Britelink MCT", src: "/images/tenants/britelink-mct.avif" },
  { name: "Strategic Partners Group", src: "/images/tenants/strategic-partners-group.avif" },
  { name: "Momentum", src: "/images/tenants/momentum.png" },
  { name: "Oxior", src: "/images/tenants/oxior.png" },
  { name: "Phakamo Holdings", src: "/images/tenants/phakamo-holdings.jpg" },
  { name: "PR House", src: "/images/tenants/pr-house.jpg" },
  { name: "RI", src: "/images/tenants/ri.webp" },
  { name: "Roi", src: "/images/tenants/roi.png" },
  { name: "SANBS", src: "/images/tenants/sanbs.jpg" },
  { name: "SPX Flow", src: "/images/tenants/spx-flow.png" },
  { name: "Stellantis", src: "/images/tenants/stellantis.png" },
  { name: "Sungrow", src: "/images/tenants/sungrow.jpg" },
  { name: "Syntegon", src: "/images/tenants/syntegon.png" },
  { name: "Tenova", src: "/images/tenants/tenova.jpg" },
  { name: "Vesa", src: "/images/tenants/vesa.jpg" },
];
